# Generated by Django 4.0.3 on 2022-03-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DouBan_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=128)),
                ('like', models.IntegerField()),
                ('collect', models.IntegerField()),
                ('score', models.FloatField()),
                ('url', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Lin_Fanfiction_And_Section_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('view', models.IntegerField()),
                ('like', models.IntegerField()),
                ('reply', models.IntegerField()),
                ('score', models.FloatField()),
                ('url', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Lin_Video_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('view', models.IntegerField()),
                ('like', models.IntegerField()),
                ('coin', models.IntegerField()),
                ('collect', models.IntegerField()),
                ('score', models.FloatField()),
                ('url', models.CharField(max_length=128)),
            ],
        ),
    ]
